[package]
name = "kvs"
version = "0.1.0"
authors=["Surya K S <suryasuresh9876543@gmail.com"]
description="A key-value store"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
